# This file is auto-generated by filter_and_save_stocks_pullback_bearish()
selected_stocks_pullback_bearish = [
    'DABUR',
    'ULTRACEMCO',
    'HINDUNILVR',
    'BRITANNIA',
    'MARUTI',
    'AIAENG',
    'LTTS',
    'IDBI',
    'GRASIM',
]
